maxmotif: maxmotif.c seq.c queue.c itemset.c problem.c
	gcc -O3 -Os -DINT_64 -DWEIGHT -o maxmotif maxmotif.c -lm
	gcc -O3 -Os -DSEQ_CHAR_SHORT -o maxmotif16 maxmotif.c -lm
	gcc -O3 -Os -DSEQ_CHAR_LONG -o maxmotif32 maxmotif.c -lm






